### ISSUE TITLE
Android 6.0 "call requires permission which may be rejected by user"

### ISSUE THREAD

**Issue by daniftodi** [traccar/traccar-client-android#187]
Hi,

In file SimplePositionProvider.java when methods "locationManager.requestLocationUpdates()" and "locationManager.removeUpdates()" are called at runtime is thrown and exception that says:

"Call requires permission which may be rejected by user".

There is a fix for this problem ( replace methods "startUpdates()" and "stopUpdates()" with:

``` java
    public void startUpdates() {
        if(locationManager != null) {
            if (checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED
                    || checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
                locationManager.requestLocationUpdates(type, period, 0, this);
            }
        }
    }
```

``` java
    public void stopUpdates() {
        if(locationManager != null) {
            if (checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED
                    || checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED) {

                locationManager.removeUpdates(this);
            }
        }
    }
```

**Comment by tananaev** [comment]
Why would it throw exception?

**Comment by daniftodi** [comment]
If you are using the Android SDK API Level 23, it requires you to check for permission for features right before you use them, that's why it gives you an error, even when you ask for permission on the manifest file.

**Comment by tananaev** [comment]
There is already permission check in the `MainActivity`.

**Comment by daniftodi** [comment]
Please read this: http://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en

**Comment by tananaev** [comment]
Please point out exactly which part I should read. I know about Android M permissions.

**Comment by daniftodi** [comment]
From "Check For Permissions" ( http://developer.android.com/training/permissions/requesting.html  ) : 

> If your app needs a dangerous permission, you must check whether you have that permission every time you perform an operation that requires that permission. The user is always free to revoke the permission, so even if the app used the camera yesterday, it can't assume it still has that permission today.

**Comment by tananaev** [comment]
Yes, I know. And the app checks for permissions every time you start the service.

**Comment by daniftodi** [comment]
I tried with API Level 23 without explicit checking permissions and my app is crashing.

**Comment by tananaev** [comment]
Please provide steps to reproduce the issue. It works for me perfectly on API 23.
