### ISSUE TITLE
Duplicate entries with incorrect positions

### ISSUE THREAD

**Issue by diegofede** [traccar/traccar-client-android#319]
It updates every 5 minutes but the positions and every date are incorrect, it duplicates the exact same entry, same date etc for often more than 10 hours. You can see in the log plenty of duplicated entries, this happened 1 to 2 weeks ago and already updated the client to the latest version and the problem persists.

**Comment by tananaev** [comment]
There are two possibilities:

1. Device doesn't get response from server for some reason, so it keeps sending old data.

2. Your phone is returning invalid data to the app.

**Comment by DiegoGitHub1** [comment]
Interesting, will look into the configuration of the phone, what do you suggest to look for?

I know that the GPS of the phone works as intended in other apps.

Can it be time missmatch? If I recall correctly I was able to modify the timezone in the server but now I don't find that option.

**Comment by garyvdm** [comment]
3rd possibility: Accuracy is on medium, so using network provider, and keeps getting the same cellphone tower.

**Comment by DiegoGitHub1** [comment]
If that's the case the date would change constantly but it only duplicates.

**Comment by tananaev** [comment]
How do you know that GPS on your phone returns correct time? In which app have you verified that? How do you know that the app uses GPS time and now phone time?

As for time zones, as long as they are configured correctly on both sides, it doesn't really matter if they are different. Everything should work fine.

**Comment by DiegoGitHub1** [comment]
I have not verified the times, only a navigation app, but I will check that side of the problem. Anything more you think I should look for? Also, it randomly stopped working as intended and it worked fine for months.

**Comment by DiegoGitHub1** [comment]
I however changed the settings on the client some time ago, I tried network and gps and probably 2 days later this problem arose, so I don't think that's it. Since then I configured back to gps only and the problem persists even after updating.

**Comment by garyvdm** [comment]
Provider setting is gone. It's replaced by a new accuracy setting. What is your accuracy setting set to?

**Comment by DiegoGitHub1** [comment]
Is on high too.

**Comment by DiegoGitHub1** [comment]
I checked the log of the client and it says something along the lines that it failed to send (can't say the exact text because its not in english), a lot of times.

**Comment by tananaev** [comment]
It means that either client couldn't connect to the server, or server didn't respond with OK response.
