### ISSUE TITLE
Implementation of fetch location frequency.

### ISSUE THREAD

**Issue by crooksey** [traccar/traccar-client-android#324]
Before I go ahead and write the code for this, I wanted to see how welcome it would be...

Currently in the android application you can simply set the frequency in which to report to the server, however for my use case (and I imagine others) So I thought about...

Implementing a feature so traccar could fetch/log its current location (and store it temporarily) then set the frequency in which to report to the server.

For example, in Android you can set location services to only use GPS, the app could then be set to log its location every 5 seconds (for example) and then send all events to the server every 10 minutes (for example).

But with the current setup it would appear you can only set both to happen at the same time.

Let me know your thoughts before I start this

**Comment by tananaev** [comment]
Is there any specific reason you want to do it? It doesn't really make much sense to me.

Also, we want to keep Android and iOS the same. If you plan to implement something in Android, we need iOS version as well.
