### ISSUE TITLE
Reading of IMEI from the device and displaying it on the device ID 

### ISSUE THREAD

**Issue by tanhaoze24** [traccar/traccar-client-android#359]
Upon first download and startup of the traccar client app on android, is the number shown on the deviceID randomly generated? If so, which part of the android source code can i modify so that the app is able to read the device IMEI and display it on the deviceID on first startup of the app?

**Comment by tananaev** [comment]
It is randomly generated. You can check early versions of Traccar Client. We used to use IMEI number as an id.

**Comment by tanhaoze24** [comment]
Thanks. For the first few versions, there is no downloadable apk, am i able to import the source code on android studio ide and build the apk from there?

**Comment by tananaev** [comment]
Yes, of course. I was talking about source code.

**Comment by oliv3** [comment]
@tananaev Which version are you referring to ? I can't find code any getting the IMEI and using it for KEY_ID. All I have is KEY_ID with a default value set to null. Thanks !

**Comment by tananaev** [comment]
Take the earliest tag for an example.

**Comment by oliv3** [comment]
@tananaev Thanks, just found https://github.com/traccar/traccar-client-android/commit/73c97f80cd1d99e770507a505be97913879be127.
