### ISSUE TITLE
Android Source code about retrieving random number generated

### ISSUE THREAD

**Issue by tanhaoze24** [traccar/traccar-client-android#361]
Relatively new to java coding, may i know which java class am i able edit so that instead of getting a random number shown on the device ID, i am able  to retrieve the IMEI from the device in the android source code

**Comment by tanhaoze24** [comment]
and also is there a way to implement a feature where by the server sets the frequency for the device, and it configures the traccar client to its desired frequency set by the server

**Comment by tananaev** [comment]
What are you creating another thread? You already asked this in #359.

**Comment by oliv3** [comment]
@tanhaoze24 Sending commands from the server to the client is not possible at the moment.
I have some ideas for that but no time to work on this feature right now.

**Comment by oliv3** [comment]
@tanhaoze24 See https://github.com/traccar/traccar-client-android/commit/73c97f80cd1d99e770507a505be97913879be127 for an example of how to get the IMEI.

**Comment by tanhaoze24** [comment]
@tananaev sorry about that, didnt see in my previous thread that @oliv3 has commented on where to get the code for IMEI. Thanks anyway.

**Comment by tanhaoze24** [comment]
@oliv3 how do i implement this into the latest version, as the java use in 73c97f8 is traccaractivity.java, whereas the latest version has three , mainfragment, mainactivity and mainapplication

**Comment by oliv3** [comment]
@tanhaoze24 Right, code has split so you'll have to backport this feature. Why do you want to do that anyway ? It's been done then removed, so @tananaev had reasons for doing so.

@tananaev BTW, is see
https://github.com/traccar/traccar-client-android/blob/64687b26c21bf4dfed56eae2be7f3afd8a1495f6/app/src/main/java/org/traccar/client/PositionProvider.java#L64
when it's null everywhere else. I can sync this in https://github.com/traccar/traccar-client-android/pull/356 if you want.

**Comment by tananaev** [comment]
Just FIY, it's been removed for two reasons:

1. To make it consistent with iOS.
2. To not request "phone calls" permission from user.

**Comment by oliv3** [comment]
Sure I knew for 2. I was saying that for @tanhaoze24' curiosity.

**Comment by tanhaoze24** [comment]
@oliv3 trying to implement a plug and play feature for the app whereby we have 100 devices, so all we have to do is key in the IMEI number to server for the Device ID and install app on the devices, instead of getting a random number generated.

In version 2.9 the reading of PHONE_STATE is used here
`private void initPreferences() {
        PreferenceManager.setDefaultValues(this, R.xml.preferences, false);

        TelephonyManager telephonyManager = (TelephonyManager) getSystemService(Context.TELEPHONY_SERVICE);
        String id = telephonyManager.getDeviceId();

        SharedPreferences sharedPreferences = getPreferenceScreen().getSharedPreferences();

        if (!sharedPreferences.contains(KEY_ID)) {
            sharedPreferences.edit().putString(KEY_ID, id).commit();
        }
        findPreference(KEY_ID).setSummary(sharedPreferences.getString(KEY_ID, id));

        sharedPreferences.edit().putBoolean(KEY_STATUS, isServiceRunning()).commit();
    }`

In latest version this function has been changed,
` private void initPreferences() {
        PreferenceManager.setDefaultValues(getActivity(), R.xml.preferences, false);

        if (!sharedPreferences.contains(KEY_DEVICE)) {
            String id = String.valueOf(new Random().nextInt(900000) + 100000);
            sharedPreferences.edit().putString(KEY_DEVICE, id).apply();
            ((EditTextPreference) findPreference(KEY_DEVICE)).setText(id);
        }
        findPreference(KEY_DEVICE).setSummary(sharedPreferences.getString(KEY_DEVICE, null));`

So do i make the change at this function? especially now with the need to do request permission due to API level, the revert will be different. Will be useful if u can assist me @oliv3

**Comment by oliv3** [comment]
Looks like you found the place.
You'll have to add the permission request in the manifest also.

**Comment by tanhaoze24** [comment]
` findPreference(KEY_DEVICE).setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
            @Override
            public boolean onPreferenceChange(Preference preference, Object newValue) {
                return newValue != null && !newValue.equals("");
            }
        });`

does this affect ?

**Comment by oliv3** [comment]
@tanhaoze24 Can't help more, sorry.

**Comment by tanhaoze24** [comment]
hi thanks @oliv3 will be closing the thread, succesfully implement getting IMEI in the latest version
