### ISSUE TITLE
Configuring frequency from server response

### ISSUE THREAD

**Issue by FreshAF123** [traccar/traccar-client-android#365]
From requestmanager, i am able to get my server response which is the frequency in JSON format, i have parsed it, how do i set it to the KEY_INTERVAL? isit by sharedpreferences?

this is my code:
```java
while ((inputLine = bufferedReader.readLine()) != null) {
                if (connection.getResponseCode() == 200) {
                    buffer.append(inputLine);
                    JSONObject response = new JSONObject(buffer.toString());
                    freq = response.getString("frequency");
                    StatusActivity.addServerMessage("frequency: " + freq); //logging
```

**Comment by oliv3** [comment]
https://github.com/traccar/traccar-client-android/blob/1b93619e64988e3ace7b7627c58d7e3ec30b53f6/app/src/main/res/values/strings.xml#L12-L13

I guess it's "interval" you want to set, not "frequency".

**Comment by oliv3** [comment]
KEY_INTERVAL is a SharedPreferences key, right.
