### ISSUE TITLE
when status turned on, two location update is sent instead of one

### ISSUE THREAD

**Issue by FreshAF123** [traccar/traccar-client-android#370]
When i first turn on the status, i will see two location updates instead of one, why is this so or how do i solve it? Is the first location update a buffer or a previous saved location

**Comment by FreshAF123** [comment]
![screenshot_20181003-144229 1](https://user-images.githubusercontent.com/43231504/46394249-22ff4800-c71b-11e8-9da7-6aec2d7e06c0.png)

**Comment by tananaev** [comment]
What are the settings in the app?

**Comment by FreshAF123** [comment]
Frequency 30 , distance and angle 0

**Comment by tananaev** [comment]
It might be that device reports outdated location first and then current one.

**Comment by FreshAF123** [comment]
is there a way perhaps to not want the device report outdated location first, but immediately the current one?

**Comment by FreshAF123** [comment]
cause when i tried it on the original v5.11 sometimes it happens too like when i start the service it will automatically send 2 location updates

**Comment by tananaev** [comment]
I don't see a big issue with it. Outdated location doesn't really affect anything on the server side. If you can find a good reason, we can consider it.
