### ISSUE TITLE
Not Background

### ISSUE THREAD

**Issue by CcSanchez** [traccar/traccar-client-android#373]
Good morning compile the application and I have installed it in different cell phones the problem I have is that in some it does not activate in the background ... Thanks

**Comment by tananaev** [comment]
You need to check Android logs for more information.

**Comment by oliv3** [comment]
Doze mode issue ?

**Comment by CcSanchez** [comment]
How can I check the logs of the application on the devices?

**Comment by tananaev** [comment]
Using logcat tool.
