### ISSUE TITLE
is there a log file after installing the app?

### ISSUE THREAD

**Issue by FreshAF123** [traccar/traccar-client-android#378]
is there any other way i can check the logs other than using the logcat in android studio's ide?

**Comment by tananaev** [comment]
If your phone is rooted, there are many apps that you can use.

**Comment by FreshAF123** [comment]
so other than logcat and rooting, there is no other way?

**Comment by tananaev** [comment]
What kind of way are you looking for?

**Comment by FreshAF123** [comment]
having a logcat text file of the application in the device storage? is there a way to do this so i can keep track on the device instead of using the IDE's logcat

**Comment by FreshAF123** [comment]
another issue is that im unable to find the package name in the internal storage of my android device after installing it

**Comment by tananaev** [comment]
There is no text file for it. And even if there was, it would require root to access it anyway.

**Comment by FreshAF123** [comment]
what about not being able to find the package name in the storage of android device?

**Comment by tananaev** [comment]
I can't say anything about off the top of my head. Feel free to investigate and read about it further.
