### ISSUE TITLE
Notification to show that service is running can not be seen

### ISSUE THREAD

**Issue by FreshAF123** [traccar/traccar-client-android#379]
Using a galaxy tab s2 with android version 7.0.0, i am unable to see the notification on the notification bar, why is this so?
![screenshot_20181023-152711](https://user-images.githubusercontent.com/43231504/47343277-57da3b80-d6d8-11e8-85b0-e1ef5452fc25.png)

**Comment by tananaev** [comment]
What notification are you expecting to see?

**Comment by FreshAF123** [comment]
the black traccar icon and a message that shows service running, i tried it on my samsung s8+ and it showed the service running notification

**Comment by tananaev** [comment]
It's only shown on newer versions of Android.

**Comment by FreshAF123** [comment]
its only shown on newer versions of android because of this,

`if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            ContextCompat.startForegroundService(this, new Intent(this, HideNotificationService.class));
        } */`

**Comment by tananaev** [comment]
That's because most people don't want to see that notification.

**Comment by FreshAF123** [comment]
i see i see, last question is the shortcut activity also meant for newer versions of android? because i cant seem to get the shortcut features

**Comment by tananaev** [comment]
It should work on all version. Try to find shortcuts in widgets menu.

**Comment by FreshAF123** [comment]
got it, thanks alot!
