### ISSUE TITLE
5.17 Update on Lineageos stopps sending location updates

### ISSUE THREAD

**Issue by vsatmydynipnet** [traccar/traccar-client-android#391]
updated one of my LineageOS Phones (Samsung A5) and one Tablet with LineageOS, both without Google stuff, to 5.17. Now they dont sent location updates anymore. the other devices running 5.16 works fine.

**Comment by tananaev** [comment]
Have you installed APK file? For APK version there is absolutely not difference between 5.16 and 5.17.

**Comment by vsatmydynipnet** [comment]
I downloaded the apk from github now and installed it on both devices. will test today and report back.

**Comment by tananaev** [comment]
You can find it in the code. The only difference is that Google Play version uses Google fused location provider.
