### ISSUE TITLE
 No strings for translation

### ISSUE THREAD

**Issue by Valdnet** [traccar/traccar-client-android#393]
There are no translations for the following words:
```
  <string name="settings_accuracy_title">Location accuracy</string>
  <string name="settings_accuracy_summary">Desired location accuracy</string>
  <string name="settings_accuracy_high">High</string>
  <string name="settings_accuracy_medium">Medium</string>
  <string name="settings_accuracy_low">Low</string>
```

**Comment by tananaev** [comment]
You are welcome to provide translations for those:

https://www.transifex.com/traccar/traccar/

**Comment by Valdnet** [comment]
Transifex translates these words but is missing in the application.
See for yourself: https://github.com/traccar/traccar-client-android/blob/master/app/src/main/res/values-pl/strings.xml

**Comment by tananaev** [comment]
If it's update on transifex then no action is required. It will be included with the next app release.

**Comment by Valdnet** [comment]
OK.  Only that the versions came out new and there are no translations  😉 

This is still missing
```
  <string name="status_network_online">Network online</string>
  <string name="status_network_offline">Network offline</string>
```
