### ISSUE TITLE
Location not sent when using a VPN

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar-client-android#396]
Using 5.18, client stops sending locations when VPN is turned on.
Turning VPN off, locations are sent again.
Is this a known issue ?

**Comment by tananaev** [comment]
Not that I know of.

**Comment by oliv3** [comment]
Well then you have an issue. Using a VPN, all traffic works flawlessly, except for Traccar client.

**Comment by tananaev** [comment]
Have you solved the issue?

**Comment by oliv3** [comment]
Why would I close an unresolved issue ?

**Comment by tananaev** [comment]
Can you send a pull request with the fix?
