### ISSUE TITLE
Error sending time (-1 hour)

### ISSUE THREAD

**Issue by Valdnet** [traccar/traccar-client-android#397]
Error sending the location point time to the server. The difference is one hour back.

Time and time zone on your smartphone is set to automatic download (GMT + 02: 00). In the status of the Traccar application, the time of sending the location is correct.

App:
Traccar v5.18
Android v4.4.4
Sony Xperia E2003

**Comment by tananaev** [comment]
Timezone must be incorrect somewhere on the device, server or browser.

**Comment by Valdnet** [comment]
The time zone on the device, server and browser are correct.

The time sent from 3 other devices by the Traccar application is correct. Only with Sony Xperia is the time difference of 1 hour.

**Comment by Valdnet** [comment]
The date and time is sent from the GPS location, which is delayed by 1 hour. If I set GMT +3, sending the time is correct. However, the system time is shifted 1 hour forward.
