### ISSUE TITLE
Select Position BUG

### ISSUE THREAD

**Issue by SaJeTek-Developer** [traccar/traccar-client-android#400]
v5.19
In the selectPosition method of the DatabaseHelper class
`SELECT * FROM position ORDER BY id LIMIT 1` is only selecting the first position all the time. I had to change to `SELECT * FROM position ORDER BY id DESC LIMIT 1` and then this worked for me. I was then able to get the messages in our backend whereas i was only getting one every time in installed the app..

This was because messages are sorted based on timestamp and the timestamp was always the same.

**Comment by tananaev** [comment]
It's not a bug. Position are uploaded in the chronological order. That's intended behavior.
