### ISSUE TITLE
New translations from Transifex

### ISSUE THREAD

**Issue by Valdnet** [traccar/traccar-client-android#402]
I noticed that before the release of the new version of the application, no new translations of descriptions from Transifex are downloaded. The last update was **5 months ago**.

Is this an oversight or an error?

**Comment by tananaev** [comment]
It could have been a minor update in which case we don't update translations.

**Comment by Valdnet** [comment]
That is very bad. Translations are constantly changing, just like the source code of the application :wink: 
Users expect a good translation of the application. And they are waiting for his corrections.
