### ISSUE TITLE
Dialing 8722... number is not opening the hidden app

### ISSUE THREAD

**Issue by vaskovasilev** [traccar/traccar-client-android#407]
Hello dear team,
I have installed the hidden version and tried to open it with dialing the number that you have provided, also opening traccar / hidden..
Nothing is happening. Also there is an icon for notification so it is seen.
Please check and advise .

Thank you

**Comment by tananaev** [comment]
Have you enabled permissions? Please use forum for questions.

As for notifications, it's a limitation on newer versions of Android.

**Comment by vaskovasilev** [comment]
Hi,
i will be happy if you reply with more than one sentence :) otherwise we cannot understand each other.
which permissions, for what ? 
you can see that in forums nobody replied.

thanks !
