### ISSUE TITLE
Feature Request: "Turn off buffering" in Client Setup

### ISSUE THREAD

**Issue by ronzeiller** [traccar/traccar-client-android#411]
Hi,
for our offshore regatta we are using satelitte trackers which are sending position datas every 5 Minutes. For distances to shore within GPRS, we thaught that we could use Traccar Client to get nice position datas at the beginning and the end of the race.
Everything is set up and working fine.

But now I found out, that firstly all the old datas which could not be sent (since we left GPRS having no internet anymore) will be sent, when a boat is having internet connection again. Especially for weak signals we need all the bandwidth for getting weather datas, tracking of other competitors and so on, so we do not want to send historical datas (which we got over satellite already).

Is there a chance to get a "turn off buffering" into the setup of the client?
And, if not, is there may be an old Traccar Client version, where this buffering was not implemented?

Thank You,
Ronnie

**Comment by tananaev** [comment]
Android implementation is ready. Working on iOS.

**Comment by ronzeiller** [comment]
Thank you Anton, great!!
When do you think you will make a new version available on the Appstore?

**Comment by tananaev** [comment]
Probably in a couple of months. Need to wait for translations.
