### ISSUE TITLE
[Feature request] GPS rollover

### ISSUE THREAD

**Issue by Valdnet** [traccar/traccar-client-android#414]
I suggest you implement GPS time correction for older devices. I think Traccar users would be grateful.

Developers in PhoneTrack Android have already done this: [squash! fixup! Handle timestamp from buggy GPS sensors](https://gitlab.com/eneiluj/phonetrack-android/-/commit/79c6198e1ac77472e447a716b499ac66066ea85a).
Description of the problem: [GPS reports wrong time when affected by GPS week rollover](https://gitlab.com/LineageOS/issues/android/issues/1446)

**Comment by skaa** [comment]
I have similar problem with my old android phone.

**Comment by tananaev** [comment]
There's a server side configuration you can do to use server time.

**Comment by skaa** [comment]
Can you help me with this? I don't see any suitable option in https://www.traccar.org/configuration-file/. My positions db table: http://prntscr.com/ucs1vq (ID, PROTOCOL, DEVICEID, SERVERTIME, DEVICETIME, FIXTIME, VALID).

**Comment by tananaev** [comment]
https://www.traccar.org/forums/topic/gps-week-number-rollover-corrections/

**Comment by Valdnet** [comment]
> There's a server side configuration you can do to use server time.

@tananaev What to do if you are using a device tracking instance other than the Traccar Server?
