### ISSUE TITLE
Background Location removed in v6.7

### ISSUE THREAD

**Issue by eventhorizonnow** [traccar/traccar-client-android#424]
**Is your feature request related to a problem? Please describe.**
Background Location was removed in v6.7
This may be the cause of the problem with traccar android client NOT firing properly when Distance threshold has been exceeded (e.g. log when location changed more than 50 metres).
 
**Describe the solution you'd like**
Make Background Location available again (like in v6.5 and v6.6)
This may solve the problem with many missing locations (not logged when time and distance thresholds exceeded).

**Describe alternatives you've considered**
Tried suggestion below but see no improvement:
https://dontkillmyapp.com/samsung

**Additional context**
Tested on Samsung S21 Ultra running Android 11.

**Comment by tananaev** [comment]
Traccar Client uses foreground location, so background location is not needed.
