### ISSUE TITLE
A way to import settings(exept from deviceID)

### ISSUE THREAD

**Issue by njittam** [traccar/traccar-client-android#437]
**Is your feature request related to a problem? Please describe.**
We used traccar in an event. Where we needed to track users over the weekend. We had documentation on how to configure the app. But this was still prone to errors and cumbersome. E.G. people using http instead of https.

**Describe the solution you'd like**
I would like to be able to setup the app once(maybe in the web interface) and send them to multiple devices. Or a device can (with  a single action) retrieve the settings from a server and will only be prompted to enter their device id.

**Describe alternatives you've considered**
I think the best way is to make a QR code. And when a user scans it, the client will prompt for a device id.
other options:
* QR code
* file (however this needs to be downloaded on the device and after that be found on the device which is 2 extra actions).
* url maybe make Traccar Client the app to open this url with. this is very Difficult because every traccar instance has a different url.

**Additional context**
This feature will also be beneficial to people who need to setup multiple devices at once.

**Comment by njittam** [comment]
I now see this is a duplicate of #355

**Comment by tananaev** [comment]
Let's close then.
