### ISSUE TITLE
CPU always running even with screen off 

### ISSUE THREAD

**Issue by ippocratis** [traccar/traccar-client-android#438]
**Describe the bug**
Device  does not go in deep sleep with screen off 

**To Reproduce**
1.install traccar client and setup server and frequency
2.turn screen off wait some hours
3. 
```
adb shell dumpsys batterystats |grep -E "Time on battery"\|"Time on battery screen off"\|"Battery time remaining"\|"Screen off discharge"\|"Device deep doze discharge"\|"Device light doze discharge"\|"Device light idling"\|"Device full idling"
```

**Expected behavior**
Device should go to deep sleep after some time in screen off

**Smartphone (please complete the following information):**
 - Device: redmi note 9s 
 - OS: sparkos
 - Browser iceraver
 - Version 1.17

**Additional context**
I'm rooted so I can monitor cpu times
On any kernel manager it is obvious that the kernel cant go in  "deep sleep" state with the traccar client running

But it is also obvious from`dumpsys batterystats` that "Device full idling" and "Device deep doze discharge" are missing while using traccar

**Comment by tananaev** [comment]
Do you have wake lock enabled?

**Comment by ippocratis** [comment]
> Do you have wake lock enabled?
Yes

**Comment by ippocratis** [comment]
Should I disable that?

**Comment by tananaev** [comment]
Then why is the expectation that it's going to go into a deep sleep when you explicitly have wake lock enabled? I'm very confused.

**Comment by ippocratis** [comment]
> Then why is the expectation that it's going to go into a deep sleep when you explicitly have wake lock enabled? I'm very confused.

Wake locks does not keep the cpu running constantly

I have other services running in the backround wit he out preventing the cpu from going to sleep
Avira,ntfy,gsmcompat,naptime

Maybe the method used to request and send a location update every x seconds to serverr is not optimal idk


I see many methods here
https://developer.android.com/training/scheduling/wakelock

**Comment by ippocratis** [comment]
Anyway I disabled the wakelock toggle and see 

I.g that was placed there to prevent some oems that kill apps in the backround?

**Comment by tananaev** [comment]
I'm going to close this for now because it doesn't seem like you have a specific suggestion or a bug report. If you have a suggestions on how we can improve the login, feel free to create a new ticket and provide specific details on what you want to be changed.

**Comment by ippocratis** [comment]
> I'm going to close this for now because it doesn't seem like you have a specific suggestion or a bug report. If you have a suggestion on how we can improve the logic, feel free to create a new ticket and provide specific details on what you want to be changed.

Been monitoring since yesterday that we last spoke  the traccar log for consistent location updates. 
I've disabled the wakelock option and everything seems to work fluid. 
Device goes to light Anne deep doze normaly and the app is not killed while in the backround. 
Sorry for misunderstanding the use of the wakelock option
Thanks
And keep up
