### ISSUE TITLE
Is there a good solution to reduce the battery usuage, while maintaining accuracy? (90% usage)

### ISSUE THREAD

**Issue by Gigarange** [traccar/traccar-client-android#445]
Android: 12
LineageOS Version: 19-20230128-NIGHTLY-alioth
Traccar Client Version: 7.0
Traccar Server Version: 5.6
Location Accuracy: High
Frequency: 150 seconds
Distance: 0
Angle: 0
Offline Buffering: on
Wake Lock: on

![image](https://user-images.githubusercontent.com/90445697/222430863-22f05dd9-aa54-4257-bd67-47208adf9446.png)

**Comment by tananaev** [comment]
You can try reducing frequency. But when you're using high accuracy it's expected that it's going to use a lot of power. That's GPS module usage.

In the future please use the forum for questions.
