### ISSUE TITLE
Быстрый разряд батареии!

### ISSUE THREAD

**Issue by bc38** [traccar/traccar-client-android#446]
Очень быстро садит батарею!
почему бы не усыплять приложение пока не будета ктивности по данным акселерометра?

**Comment by tananaev** [comment]
Duplicate of #288.

**Comment by bc38** [comment]
Жрет батарею как ни в себя! 
без постоянно подключенной зарядки, приложение не жизнеспособно на устройстве

**Comment by tananaev** [comment]
Если вы включили GPS 100% времени, то естественно будет жрать батарею.

**Comment by bc38** [comment]
разве где то есть настройка выбора в процентах использования GPS?
сон сделать нельзя как в трекерах с датчиком движения?

**Comment by tananaev** [comment]
Есть настройка частоты отправки данных которая повлияет на процент использования GPS. Еще есть настройка точности.

Сделать всё можно.

**Comment by bc38** [comment]
какие есть рекомендации по частоте отправки?
т.е. я понимаю что когда устройство без движения это интервал отправки сообщения?
