### ISSUE TITLE
androidx.test:core  missing

### ISSUE THREAD

**Issue by enriqueillan** [traccar/traccar-client-android#451]
It looks that the DatabaseHelperTest is missing the package androidx.test:core

![image](https://github.com/traccar/traccar-client-android/assets/7118479/801b1d22-e0d4-494d-8527-d27a917c2f2f)

It looks like this dependency is missing

![image](https://github.com/traccar/traccar-client-android/assets/7118479/52da4e83-8d9c-4e2b-98b6-f526b162b2cf)

So I suggest to add this dependecy to the project

https://androidx.de/androidx/test/core/app/ApplicationProvider.html

**Comment by tananaev** [comment]
Good catch, thanks.
