### ISSUE TITLE
ESET Security - Traccar falsely positive categorised

### ISSUE THREAD

**Issue by M-Stenzel** [traccar/traccar-client-android#456]
**Describe the bug**
ESET Endpoint Security (ver 4.0.2.0) falsely classifies the app as virus infected.

**To Reproduce**
1. Install ESET Endpoint Security Android app
2. Try to install Traccar client (latest version) from github
3. Traccar client is categorised as virus infected
4. Installation is possible by allowing an exception 

**Expected behavior**
Traccar client app is categorised safe to install

**Smartphone**
 - Fairphone 4
 - /e/ OS 1.14

**Comment by tananaev** [comment]
What exactly is it categorized as? Does it provide details?

**Comment by M-Stenzel** [comment]
![Screenshot_20230923-193850_ESET Endpoint Security for Android](https://github.com/traccar/traccar-client-android/assets/76916440/8aa41f7e-b990-4a91-b8c1-6b5692683b02)

**Comment by tananaev** [comment]
It's telling you that it's a location monitoring app, which it is.
