### ISSUE TITLE
Location updates not happening after update to 7.2

### ISSUE THREAD

**Issue by ingestre** [traccar/traccar-client-android#458]
**Describe the bug**
Following the recent update to traccar client (7.2?) location updates are not being sent to the traccar server.

This bug occurs no matter whether WiFi or mobile data is being used.
I have tried increasing the accuracy of the reporting to High in the app. No improvement.
I also tried clearing the cache for the app. Still not working.
I have verified that the traccar server (V5.10 - latest) is accepting osmand connections using a handcrafted CURL command .
Devices using the watch protocol are not affected.
The App Status screen is showing service started/stopped/networkonline messages, but not location updates.

**To Reproduce**
1. Start the app on Xiaomi Note 8 Pro running MiUI 12 version of Android
2. Click "Status"
3. Observe no location updates

**Expected behavior**
I expect location updates to be sent at the frequency defind in the app (every 60 secs)

**Server (please complete the following information):**
 - OS: Raspbian Bullseye
 - Version: Traccer server V5.10
 - DB: MySQL/MariaDB

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 8 Pro
 - OS: MiUI 12

**Additional context**
I ensured battery saver was off for this app, and it had the "location" permission

**Comment by tananaev** [comment]
Have you checked the troubleshooting guide?

**Comment by ingestre** [comment]
[This one?](https://www.traccar.org/client-troubleshooting/) . Yes I did, but based on your steer I looked again and found this setting buried in the MIUI settings

![Screenshot_2023-11-22-14-38-06-790_com google android gms](https://github.com/traccar/traccar-client-android/assets/8740246/5c9e6b3c-58cd-43e4-8e59-eb75b9891376)

It was turned off. Turning it on made things work.

Closing this issue with the recommendation that the troubleshooting guide be updated with this particular setting (It isn't at the moment as far as I can tell)
