### ISSUE TITLE
What are the units for the reported values?

### ISSUE THREAD

**Issue by ramonsmits** [traccar/traccar-client-android#459]
The following is submitted by the client:

```
?id=string
&timestamp=int
&lat=double
&lon=double
&speed=double
&bearing=double
&altitude=double
&accuracy=double
&batt=double
```

The `timestamp` value likely is time in Linux time in seconds based on the sizes of the int but in what unit is `speed`? Is is km/h, m/h, m/s?

What does `accuracy` mean? Does this apply to both horizontal and vertical accuracy?

The values on the <https://www.traccar.org/osmand/> are not the same. For example, it lists `hdop`. Searching for this shows "horizontal dilution of precision". Does that mean `hdop` became `accuracy` and that its horizontal accuracy?

It would be useful to add this information to <https://www.traccar.org/osmand/>

**Comment by tananaev** [comment]
For questions you should use the forum instead.

**Comment by ramonsmits** [comment]
For those who land on this page. Data is available at https://developer.android.com/reference/android/location/Location

```
double lat,     // The latitude in degrees.
double lon,     // The longitude in degrees.
float speed,    // The speed at the time of this location in meters per second.
double bearing, // The bearing at the time of this location in degrees.
double altitude,// The altitude of this location in meters above the WGS84 reference ellipsoid.
float accuracy, // The estimated horizontal accuracy radius in meters of this location at the 68th percentile confidence level.
```
