### ISSUE TITLE
How does user data(status) sending to the back-end side(Admin panel)

### ISSUE THREAD

**Issue by SHUBHAMGUPTA123456** [traccar/traccar-client-android#464]
Hey,
It's working fine, but I'm unable to find how the user sends the status of Service stopped/Service running "Service Status" information to the Admin Panel(back-end services) via using API or anything else.... because I'm unable to get any Network library to use an API, please let me know if you're using API then how can I know the base URL if not using API then how in Admin Panel getting the status.

Thank you

**Comment by tananaev** [comment]
For questions you should use the forum.
