### ISSUE TITLE
What time zone is in the exported location file (.csv)?

### ISSUE THREAD

**Issue by Fragmentszz** [traccar/traccar-client-android#468]
Thank you all for your great work, this has been a fantastic project!
But I encountered some problems during the use of it.
The first is, are the locations submitted by the client (Android) to the server all based on OpenStreetMap? What time zone is in the exported location file (.csv)? It doesn't seem to be in the UTC+8 time zone I'm in. Can the map based on which the client submits the location information to the server be adjusted?
The client device is SM-G9980 (Samsung S21 Ultra), Android 14.
Both the server and client are using version 6.3.
Thank you again for your excellent work and look forward to your reply!

**Comment by Fragmentszz** [comment]
I found that the time in the web page (running on port 8082) is the correct UTC+8 time, but it seems to be wrong after exporting, is there a bug?

**Comment by tananaev** [comment]
For questions you should ask the forum.
