### ISSUE TITLE
cannot connect traccar client in android device in port 5055

### ISSUE THREAD

**Issue by 2441630833** [traccar/traccar-client-android#476]
hi,there, i can use ios version traccar client app to connect my server address port 5055, however  i cannot establish connection when i using android devices. I can receive the logs info when i am using ios traccar client app to connect, but i cannot receive any info logs when i am using android device to connect port 5055. Do i need change the port to connect? Is it because of the different protocal? Or it is irrelevent with port that i cannot receive any logs info?

**Comment by tananaev** [comment]
For questions please use the forum instead.
